### ISSUE TITLE
Use of my_bots()

### ISSUE THREAD

**Issue by kpunde** [cyweb/hammer#12]
I am using the script for firewall Testing. 
Could anyone please explain the use of (http://www.facebook.com/sharer/sharer.php?u=) and (http://validator.w3.org/check?uri=) in my_bot() function. 

I understood that in bot_hammering function we are sending http GET request, but what is use of these above 2 urls ?

Quick replies is highly appreciated.

**Comment by leovarmak** [comment]
Looks like the developer is trying to perform a DDoS everytime someone uses this script

**Comment by sundowndev** [comment]
>Actually, it seems to be harnessing the Facebook crawler and HTML/CSS validator's requests in order to amplify the attack.
The script appends the URL of the DDoS target to the http://validator.w3.org/check?uri= string. e.g. http://validator.w3.org/check?uri=http://www.THISSERVERISD00M3D.com
Similar to this concept:
http://chr13.com/2014/04/20/using-facebook-notes-to-ddos-any-website/
