### ISSUE TITLE
THIS SCRIPT CONTAINS CODE TO ATTACK `www.facebook.com` and `validator.w3.org`.

### ISSUE THREAD

**Issue by dono** [cyweb/hammer#13]

**Comment by Anonyvius** [comment]
so, is it safe? or delete these lines?

**Comment by getPoland** [comment]
> 
> 
> so, is it safe? or delete these lines?

I think it could be safe but you have to be Ob-Sec so don't leave any hint's :D
I can hack everything, you just have to stay invisible
