### ISSUE TITLE
YouTube Video is blocked

### ISSUE THREAD

**Issue by iamstefin** [cyweb/hammer#31]
YouTube video is blocked

**Comment by noahbroyles** [comment]
Yeah, please fix it! 
<sub>Or write a real README</sub>

**Comment by IamStefin** [comment]
> Yeah, please fix it!
> Or write a real README

I don't think this project is maintained by anyone

**Comment by noahbroyles** [comment]
> I don't think this project is maintained by anyone
That's too bad

**Comment by meizumx4pkwn** [comment]
The cmd is 
$ python hammer.py -s [ip Address] -t 135
...
🔨 hammer🔨 need the Name Server of a website which you want to attack...
To get the Name Server...just type
$ nslookup example.com
Note the IP Address of that Website

then
$ cd Hammer
$ python hammer.py -s [ip Address] -t 135
example:
$ python hammer.py -s 123.45.67.89 -t 135
