### ISSUE TITLE
Can you improve this can use with proxy?

### ISSUE THREAD

**Issue by johnsmeeth** [cyweb/hammer#4]
This script work fine but it can only run on a short time then server will block that ip, it will work better if it can use via proxy list. It'll more effect

**Comment by cyweb** [comment]
it is possible but i don't recomend proxy list. i think to add tor service to hammer script for next days. but first i need free time. thanks your advice.

**Comment by LandonPowell** [comment]
Does Torify not already work witih Hammer?
