### ISSUE TITLE
Video Is Down

### ISSUE THREAD

**Issue by RocketNinja15** [cyweb/hammer#40]
The title

**Comment by DrJfrost** [comment]
it's been 3 months and it's still down lol

**Comment by JaxGamez** [comment]
Leave a comment

**Comment by flavionameless** [comment]
Python hammer.py -s(ip) -p(port) -t(turbo)

**Comment by CHLA9LOLOOO** [comment]
Where i can find the video ?

**Comment by efe3535** [comment]
> Where i can find the video ?

Until they reupload you can't see video but @flavionameless explained it correctly.

**Comment by Mr-Pantex** [comment]
www.xnxx.cim

Pada tanggal Rab, 31 Mar 2021 15.07, Ahmet Efe AKYAZI <
***@***.***> menulis:
