### ISSUE TITLE
Great tool!

### ISSUE THREAD

**Issue by MademoiselleVictoire** [cyweb/hammer#51]
Thank you so much! Works flawless! Code more like this please! I don't understand people complaining. If you don't know how to run simple python script then this tools is definitely not for you! And GitHub is not your place! He already stated tool is for administrative educational purposes. Good video is down, so kids don't play around with it.

**Comment by v3rz** [comment]
Why did you make this in the first place to close it then reopen it?
Also you do realize there's simple usage documentation anyways, right??
