### ISSUE TITLE
Work? 

### ISSUE THREAD

**Issue by XM1N21KR1** [cyweb/hammer#56]
I don't know if it works or not but..I'm trying DDoS my own website and yeah, my website is down, how to fix it huhu

**Comment by roman0018** [comment]
U're a genius hahahahaha
Il gio 14 apr 2022, 4:10 PM XM1N21KR1 ***@***.***> ha scritto:

**Comment by XM1N21KR1** [comment]
> 

hahaha, do these tools work? I don't know because I'm a Script kiddie

**Comment by roman0018** [comment]
Bro probably u don't have a server for your website

Il ven 15 apr 2022, 12:59 PM XM1N21KR1 ***@***.***> ha
scritto:
