### ISSUE TITLE
Line 9 No Module Named Queue

### ISSUE THREAD

**Issue by L05TW0LF** [cyweb/hammer#7]
hammer.py -s xxxxxxxxxx -p 80 -t 135
Traceback (most recent call last):
  File "C:\Users\User\Desktop\hammer\hammer.py", line 9, in <module>
    from queue import Queue
ImportError: No module named queue

C:\Users\User\Desktop\hammer>

This is what happens when I tried to use this script on my own IP, can anyone tell me how to fix this?

**Comment by Berk-Kaya** [comment]
Use python3
